# Generated by Django 4.1.7 on 2023-02-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("price", models.IntegerField()),
                ("no_of_bathrooms", models.IntegerField()),
                ("no_of_bedrooms", models.IntegerField()),
                ("square_footage", models.IntegerField()),
                ("address", models.CharField(max_length=150)),
            ],
        ),
    ]
